### ISSUE TITLE
Please bump versions in Docker Hub to reflect recent security update

### ISSUE THREAD

**Issue by dsmith4-godaddy** [redis/docker-library-redis#419]
The version bumps in https://github.com/redis/docker-library-redis/pull/418 haven't yet made it to Docker Hub. https://hub.docker.com/_/redis still shows the latest containers as 6.2.14/7.2.5/7.4.0.

Would whoever is responsible for triggering this process, please build and publish updated containers, so that users of those images can pick up the latest security updates?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/17673 (the updated images are all built and published now)

**Comment by dsmith4-godaddy** [comment]
And so they are. Thank you!
